import json
import os
import re
import sqlite3
import sys
from datetime import date
from urllib.request import Request, urlopen

from alert import send_alert

RELEASES_DB = "releases.db"
LOGS_DB = "logs.db"


def _load_dotenv(path=".env"):
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, val = line.partition("=")
                os.environ.setdefault(key.strip(), val.strip())
    except FileNotFoundError:
        pass


_load_dotenv()
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")

VOICE_PROMPTS = {
    "analogy_90s":      "Rewrite this analogy in late 90s R&B and hip hop slang. Use phrases like 'all that and a bag of chips', 'da bomb', 'feel me', 'no doubt', 'word', 'straight up', 'mad [adjective]', 'on the real', 'that joint is', 'for real for real'. One sentence, no quotes.",
    "analogy_genz":     "Rewrite this analogy in Gen Z slang — lowkey, slay, no cap, vibe check. One sentence, no quotes.",
    "analogy_medieval": "Rewrite this analogy as if proclaimed by a medieval town crier. One sentence, no quotes.",
    "analogy_aifluff":  "Rewrite this analogy as hollow AI corporate marketing speak — synergies, paradigms, leverage. One sentence, no quotes.",
    "analogy_plain":    "Rewrite this analogy as a plain, clear one or two sentence explanation a normal person would understand. No slang, no jargon, no style — just simple everyday language. No quotes.",
}

# Columns that cannot be regenerated by AI — mark unfixable immediately
UNFIXABLE_COLUMNS = {"title", "link", "sources_json", "raw_titles_json"}


def _haiku(prompt, max_tokens=300):
    data = json.dumps({
        "model": "claude-haiku-4-5",
        "max_tokens": max_tokens,
        "messages": [{"role": "user", "content": prompt}],
    }).encode()
    req = Request(
        "https://api.anthropic.com/v1/messages",
        data=data,
        headers={
            "Content-Type": "application/json",
            "x-api-key": ANTHROPIC_API_KEY,
            "anthropic-version": "2023-06-01",
        },
    )
    with urlopen(req, timeout=20) as resp:
        result = json.loads(resp.read())
    return re.sub(r"^#+\s*", "", result["content"][0]["text"].strip())


def _extract_column(details):
    m = re.search(r"Column '([^']+)'", details)
    return m.group(1) if m else None


def _regen_summary(title):
    prompt = (
        f"Summarize this software release or blog post for a general audience.\n"
        f"Title: {title}\n"
        f"Write 1-3 sentences in plain English. "
        f"If you have very little information, write one short sentence based on the title alone. "
        f"Respond with the summary only, no quotes, no markdown."
    )
    return _haiku(prompt, 200)


def _regen_analogy(title, summary):
    context = summary or title
    prompt = (
        f"Write one corny everyday analogy that describes this software change in simple terms.\n"
        f"Title: {title}\nSummary: {context}\n"
        f"One sentence only, no quotes."
    )
    return _haiku(prompt, 120)


def _regen_voice(base_analogy, col):
    instruction = VOICE_PROMPTS[col]
    return _haiku(f"{instruction}\n\nOriginal: {base_analogy}", 120)


def _regen_reddit_summary(company, raw_titles_json):
    try:
        titles = json.loads(raw_titles_json)
    except Exception:
        return None
    if not titles:
        return None
    lines = "\n".join(f"- {t}" for t in titles[:60])
    prompt = (
        f"These are recent post titles from {company}'s community forums and social channels:\n\n"
        f"{lines}\n\n"
        f"Write 3-4 sentences summarizing community sentiment about {company}. "
        f"Cover what users love, what frustrates them, any bugs or pain points, and overall tone. "
        f"Be specific and direct. No headers, no bullet points, no markdown, no em dashes."
    )
    return _haiku(prompt, 250)


def fix_releases_or_blog(table, row_id, col, rel_con):
    """Fix one column on releases or blog_posts. Returns (success, message)."""
    row = rel_con.execute(
        f"SELECT title, summary, analogy FROM {table} WHERE id=?", (row_id,)
    ).fetchone()
    if not row:
        return False, "Row not found"
    title, summary, analogy = row

    if col == "summary":
        text = _regen_summary(title)
        if not text or "Summary unavailable" in text:
            return False, f"Haiku returned unusable summary: {text!r}"
        rel_con.execute(f"UPDATE {table} SET summary=? WHERE id=?", (text, row_id))
        return True, f"Regenerated summary ({len(text)} chars)"

    if col == "analogy":
        text = _regen_analogy(title, summary)
        if not text:
            return False, "Haiku returned empty analogy"
        rel_con.execute(f"UPDATE {table} SET analogy=? WHERE id=?", (text, row_id))
        return True, f"Regenerated analogy"

    if col in VOICE_PROMPTS:
        base = analogy
        if not base:
            # Regenerate base analogy first so we have something to revoice
            base = _regen_analogy(title, summary)
            if not base:
                return False, "Could not regenerate base analogy needed for voice variant"
            rel_con.execute(f"UPDATE {table} SET analogy=? WHERE id=?", (base, row_id))
        text = _regen_voice(base, col)
        if not text:
            return False, f"Haiku returned empty voice variant for {col}"
        rel_con.execute(f"UPDATE {table} SET {col}=? WHERE id=?", (text, row_id))
        return True, f"Regenerated {col}"

    return False, f"Column '{col}' is not auto-fixable"


def fix_reddit(row_id, col, rel_con):
    """Fix one column on reddit_sentiment. Returns (success, message)."""
    row = rel_con.execute(
        "SELECT company, summary, raw_titles_json FROM reddit_sentiment WHERE id=?", (row_id,)
    ).fetchone()
    if not row:
        return False, "Row not found"
    company, summary, raw_titles_json = row

    if col == "summary":
        if not raw_titles_json:
            return False, "raw_titles_json is empty — cannot regenerate summary without source data"
        text = _regen_reddit_summary(company, raw_titles_json)
        if not text:
            return False, "Haiku returned empty community summary"
        rel_con.execute(
            "UPDATE reddit_sentiment SET summary=? WHERE id=?", (text, row_id)
        )
        return True, f"Regenerated reddit summary ({len(text)} chars)"

    return False, f"Column '{col}' on reddit_sentiment is not auto-fixable"


def process_error(err_id, table_name, row_id, error_type, details, rel_con, log_cur):
    """Attempt a fix and update logs.db. Returns (fixed_status, message)."""
    if error_type == "dead_url":
        log_cur.execute(
            "UPDATE errors SET fixed=-1 WHERE id=?", (err_id,)
        )
        return -1, "Dead URL — marked unfixable"

    col = _extract_column(details)
    if col is None:
        log_cur.execute("UPDATE errors SET fixed=-1 WHERE id=?", (err_id,))
        return -1, f"Could not parse column name from details: {details!r}"

    if col in UNFIXABLE_COLUMNS:
        log_cur.execute("UPDATE errors SET fixed=-1 WHERE id=?", (err_id,))
        return -1, f"Column '{col}' cannot be regenerated by AI"

    try:
        if table_name == "reddit_sentiment":
            success, msg = fix_reddit(row_id, col, rel_con)
        elif table_name in ("releases", "blog_posts"):
            success, msg = fix_releases_or_blog(table_name, row_id, col, rel_con)
        else:
            log_cur.execute("UPDATE errors SET fixed=-1 WHERE id=?", (err_id,))
            return -1, f"Unknown table '{table_name}'"

        if success:
            log_cur.execute("UPDATE errors SET fixed=1 WHERE id=?", (err_id,))
            return 1, msg
        else:
            log_cur.execute("UPDATE errors SET fixed=-1 WHERE id=?", (err_id,))
            return -1, msg

    except Exception as e:
        log_cur.execute("UPDATE errors SET fixed=-1 WHERE id=?", (err_id,))
        return -1, f"Exception during fix: {e}"


def main():
    if not ANTHROPIC_API_KEY:
        print("ANTHROPIC_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    rel_con = sqlite3.connect(RELEASES_DB)
    log_con = sqlite3.connect(LOGS_DB)
    log_cur = log_con.cursor()

    errors = log_cur.execute(
        "SELECT id, table_name, row_id, error_type, details FROM errors WHERE fixed=0"
    ).fetchall()

    if not errors:
        print("No open errors found.")
        rel_con.close()
        log_con.close()
        return

    print(f"Processing {len(errors)} open error(s)...")

    fixed_ok, fixed_unfixable, fixed_failed = [], [], []

    for err_id, table_name, row_id, error_type, details in errors:
        status, msg = process_error(
            err_id, table_name, row_id, error_type, details, rel_con, log_cur
        )
        label = f"[err {err_id}] {table_name}/{row_id} {error_type}"
        if status == 1:
            print(f"  FIXED    {label}: {msg}")
            fixed_ok.append((err_id, table_name, row_id, error_type, msg))
        elif status == -1:
            print(f"  SKIP     {label}: {msg}")
            if error_type == "dead_url":
                fixed_unfixable.append((err_id, table_name, row_id, error_type, msg))
            else:
                fixed_failed.append((err_id, table_name, row_id, error_type, msg))
        rel_con.commit()
        log_con.commit()

    rel_con.close()
    log_con.close()

    total = len(errors)
    n_ok = len(fixed_ok)
    n_skip = len(fixed_unfixable)
    n_fail = len(fixed_failed)

    print(f"\nDone: {n_ok} fixed, {n_skip} unfixable (dead URLs), {n_fail} failed.")

    def _rows_block(rows):
        return "\n".join(
            f"  [{e}] {t}/{r} ({et}): {m}" for e, t, r, et, m in rows
        ) or "  (none)"

    body = (
        f"autofix.py processed {total} open error(s) from logs.db:\n\n"
        f"Fixed ({n_ok}):\n{_rows_block(fixed_ok)}\n\n"
        f"Unfixable / dead URLs ({n_skip}):\n{_rows_block(fixed_unfixable)}\n\n"
        f"Failed / could not regenerate ({n_fail}):\n{_rows_block(fixed_failed)}"
    )
    send_alert("company-tracker: autofix complete", body)


if __name__ == "__main__":
    main()
